name: Deploy Deno Build to GitHub Pages

on:
  push:
    branches:
      - main  # or your source branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v4

    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v2.3.x

    - name: Run Deno build
      run: deno task build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        # Depending on your setup, you can specify the pages repo and branch like:
        # target_repo: kevindigo/your-pages-repo
        # destination_branch: main
